"$content = @'" 
"import api from './axios';" 
"export const createContest = (data) => api.post('/api/contests', data);" 
"export const getAllContests = (params) => api.get('/api/contests', { params });" 
"export const getContest = (id) => api.get(\`/api/contests/\${id}\`);" 
"export const updateContest = (id, data) => api.put(\`/api/contests/\${id}\`, data);"  
"export const approveContest = (id) => api.post(\`/api/contests/\${id}/approve\`);"  
"export const rejectContest = (id, reason) => api.post(\`/api/contests/\${id}/reject\`, { reason });"  
"export const enterContest = (contestId, payload) => api.post(\`/api/contests/\${contestId}/enter\`, payload);"  
"export const getContestParticipants = (contestId) => api.get(\`/api/contests/\${contestId}/participants\`);" 
"export const checkUserEntry = (contestId, userId) => api.get(\`/api/contests/\${contestId}/entry/\${encodeURIComponent(userId)}\`);"  
"export const generateReferralLink = (contestId, userId) => api.post(\`/api/contests/\${contestId}/referral\`, { userId });"  
"export const getReferralStats = (contestId, userId) => api.get(\`/api/contests/\${contestId}/referral/\${encodeURIComponent(userId)}\`);"  
"export const triggerDraw = (contestId) => api.post(\`/api/contests/\${contestId}/draw\`);"  
"export const getContestWinners = (contestId) => api.get(\`/api/contests/\${contestId}/winners\`);" 
"export const getDrawLog = (contestId) => api.get(\`/api/contests/\${contestId}/draw-log\`);"  
"export const getTransparencyReport = (contestId) => api.get(\`/api/contests/\${contestId}/transparency\`);"  
"export const getAllTransparencyReports = () => api.get('/api/contests/transparency/all');"  
"export const getAdminStats = () => api.get('/api/admin/stats');"  
"export const getFraudAlerts = () => api.get('/api/admin/fraud-alerts');"  
"export const flagUser = (userId, reason) => api.post('/api/admin/flag-user', { userId, reason });" 
"'@"  
"[System.IO.File]::WriteAllText('C:\Users\Tanmay.s\Desktop\Bid-Frontend\src\api\contests.js', \$content, [System.Text.Encoding]::UTF8)"  
"Write-Host 'contests.js written:' ((Get-Item 'C:\Users\Tanmay.s\Desktop\Bid-Frontend\src\api\contests.js').Length) 'bytes'" 
