"const fs = require('fs');" 
"const content = \`import { useState } from 'react';" 
"import { useNavigate } from 'react-router-dom';" 
"import toast from 'react-hot-toast';" 
"import { createContest } from '../api/contests';" 
"import { useAuthStore } from '../store/authStore';" 
"" 
"const INITIAL_TIER = { rank: '', winnersCount: 1, prize: '' };" 
"" 
"function Field({ label, required, optional, error, children }) {" 
