import { useState, useEffect, useCallback } from 'react';
import { useParams, Link } from 'react-router-dom';
import { getTransparencyReport, getAllTransparencyReports } from '../api/contests';
import LoadingSpinner from '../components/LoadingSpinner';

/* ── Hash helper (SHA-256 visual) ────────────── */
async function sha256(str) {
  const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(str));
  return Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, '0')).join('');
}

/* ── Fairness algorithm explanation ──────────── */
const ALGORITHM_STEPS = [
  { icon: '1', title: 'Participant Pool Locked', desc: 'When the contest ends, the full list of participants is frozen. No new entries accepted.' },
  { icon: '2', title: 'Random Seed Generated', desc: 'A cryptographic seed is generated by combining: contest ID + end timestamp (ISO) + total participant count. This seed is deterministic and reproducible.' },
  { icon: '3', title: 'Fisher-Yates Shuffle', desc: 'The participant array is shuffled using the seed via a seeded PRNG (Mulberry32 algorithm). Every permutation is equally probable.' },
  { icon: '4', title: 'Winners Sliced by Tier', desc: 'After shuffle, winners are picked sequentially: Tier 1 takes slots 0..n1, Tier 2 takes next slots, and so on.' },
  { icon: '5', title: 'Result Committed', desc: 'The draw seed, shuffle order, and winner list are saved permanently in the draw log and cannot be modified.' },
];

/* ── Seed demo widget ────────────────────────── */
function SeedDemo({ report }) {
  const [hash, setHash] = useState('');
  const seed = `${report?.contestId}::${report?.endTime}::${report?.totalParticipants}`;

  useEffect(() => {
    sha256(seed).then(setHash);
  }, [seed]);

  return (
    <div className="rounded-2xl p-5 space-y-4" style={{ background: '#111114', border: '1px solid rgba(91,95,239,0.2)' }}>
      <p className="text-xs font-semibold text-[#5B5FEF] uppercase tracking-widest">Seed Construction</p>
      <div className="font-mono text-xs space-y-2">
        <div className="flex gap-3 items-start">
          <span className="text-[#6B6B78] shrink-0 w-28">Contest ID</span>
          <span className="text-[#A0A0AB] break-all">{report?.contestId ?? '—'}</span>
        </div>
        <div className="flex gap-3 items-start">
          <span className="text-[#6B6B78] shrink-0 w-28">End Time</span>
          <span className="text-[#A0A0AB]">{report?.endTime ?? '—'}</span>
        </div>
        <div className="flex gap-3 items-start">
          <span className="text-[#6B6B78] shrink-0 w-28">Participants</span>
          <span className="text-[#A0A0AB]">{report?.totalParticipants ?? '—'}</span>
        </div>
        <div className="h-px" style={{ background: 'rgba(255,255,255,0.06)' }} />
        <div className="flex gap-3 items-start">
          <span className="text-[#6B6B78] shrink-0 w-28">Raw Seed</span>
          <span className="text-[#7477F5] break-all">{seed}</span>
        </div>
        <div className="flex gap-3 items-start">
          <span className="text-[#6B6B78] shrink-0 w-28">SHA-256</span>
          <span className="text-[#22C55E] break-all text-[11px]">{hash || 'Computing…'}</span>
        </div>
      </div>
      <p className="text-[11px] text-[#6B6B78]">You can verify this hash independently using any SHA-256 tool.</p>
    </div>
  );
}

/* ── Single contest transparency ─────────────── */
function ContestReport({ id }) {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    getTransparencyReport(id)
      .then(({ data }) => setReport(data))
      .catch((err) => { if (err?.response?.status === 404) setNotFound(true); })
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) return <LoadingSpinner message="Loading draw proof…" />;
  if (notFound) return (
    <div className="text-center py-16 space-y-3">
      <span className="text-5xl">🔍</span>
      <p className="text-white font-semibold">Draw not found for this contest.</p>
      <p className="text-sm text-[#6B6B78]">The draw may not have happened yet.</p>
    </div>
  );

  const TIER_COLORS = ['#F5A623', '#A0A0AB', '#CD7F32'];

  return (
    <div className="space-y-8">
      {/* Stats row */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        {[
          { label: 'Total Participants', val: report?.totalParticipants ?? '—' },
          { label: 'Total Winners', val: report?.totalWinners ?? '—' },
          { label: 'Draw Method', val: report?.method ?? 'Seeded PRNG' },
          { label: 'Draw At', val: report?.drawnAt ? new Date(report.drawnAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—' },
        ].map(({ label, val }) => (
          <div key={label} className="rounded-xl p-4 text-center" style={{ background: '#18181C', border: '1px solid rgba(255,255,255,0.06)' }}>
            <p className="text-2xl font-bold text-white">{val}</p>
            <p className="text-xs text-[#6B6B78] mt-1">{label}</p>
          </div>
        ))}
      </div>

      {/* Seed demo */}
      <SeedDemo report={report} />

      {/* Winners by tier */}
      {(report?.tierResults ?? []).map((tier, ti) => (
        <div key={ti} className="space-y-3">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-lg flex items-center justify-center text-xs font-bold" style={{ background: `${TIER_COLORS[ti] ?? '#5B5FEF'}18`, color: TIER_COLORS[ti] ?? '#5B5FEF' }}>{tier.rank}</div>
            <h3 className="text-sm font-semibold text-white">{tier.prize}</h3>
            <span className="text-xs text-[#6B6B78]">{tier.winners?.length} winner{tier.winners?.length !== 1 ? 's' : ''}</span>
          </div>
          <div className="space-y-1.5">
            {(tier.winners ?? []).map((w, wi) => (
              <div key={wi} className="flex items-center gap-3 px-4 py-2.5 rounded-xl" style={{ background: '#18181C', border: '1px solid rgba(255,255,255,0.05)' }}>
                <span className="text-xs font-mono text-[#6B6B78] w-6">#{wi + 1}</span>
                <span className="text-sm text-[#A0A0AB] flex-1 truncate">{w}</span>
                <span style={{ color: TIER_COLORS[ti] ?? '#5B5FEF' }}>★</span>
              </div>
            ))}
          </div>
        </div>
      ))}

      {/* Full shuffle log */}
      {report?.shuffleLog && (
        <details className="rounded-xl overflow-hidden" style={{ border: '1px solid rgba(255,255,255,0.06)' }}>
          <summary className="px-4 py-3 text-sm font-medium text-[#A0A0AB] cursor-pointer hover:text-white transition-colors" style={{ background: '#18181C' }}>Full Shuffle Order (click to expand)</summary>
          <div className="p-4 max-h-64 overflow-y-auto" style={{ background: '#111114' }}>
            <pre className="text-[11px] font-mono text-[#6B6B78] whitespace-pre-wrap break-all">{JSON.stringify(report.shuffleLog, null, 2)}</pre>
          </div>
        </details>
      )}
    </div>
  );
}

/* ── All past results list ───────────────────── */
function AllReports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getAllTransparencyReports()
      .then(({ data }) => setReports(Array.isArray(data) ? data : []))
      .catch(() => setReports([]))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <LoadingSpinner message="Loading history…" />;

  if (reports.length === 0) return (
    <div className="text-center py-16 space-y-3">
      <span className="text-5xl">📜</span>
      <p className="text-white font-semibold">No completed contests yet.</p>
    </div>
  );

  return (
    <div className="space-y-3">
      {reports.map((r) => (
        <Link key={r.contestId} to={`/transparency/${r.contestId}`}
          className="flex items-center gap-4 px-5 py-4 rounded-xl hover:border-[rgba(91,95,239,0.3)] transition-all"
          style={{ background: '#18181C', border: '1px solid rgba(255,255,255,0.06)' }}>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-semibold text-white truncate">{r.contestTitle ?? r.contestId}</p>
            <p className="text-xs text-[#6B6B78] mt-0.5">{r.totalParticipants} participants · {r.totalWinners} winners · Drawn {r.drawnAt ? new Date(r.drawnAt).toLocaleDateString('en-IN') : '—'}</p>
          </div>
          <svg className="w-4 h-4 text-[#5B5FEF] shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" /></svg>
        </Link>
      ))}
    </div>
  );
}

export default function TransparencyPage() {
  const { id } = useParams();

  return (
    <div className="min-h-screen py-12 px-5" style={{ background: '#0C0C0E' }}>
      <div className="max-w-3xl mx-auto">

        {/* Header */}
        <div className="mb-10">
          {id ? (
            <Link to="/transparency" className="inline-flex items-center gap-1 text-sm text-[#6B6B78] hover:text-[#A0A0AB] mb-5 transition-colors">← All Results</Link>
          ) : (
            <Link to="/contests" className="inline-flex items-center gap-1 text-sm text-[#6B6B78] hover:text-[#A0A0AB] mb-5 transition-colors">← Contests</Link>
          )}
          <span className="text-[11px] font-semibold text-[#5B5FEF] uppercase tracking-widest">Provably Fair</span>
          <h1 className="text-3xl font-bold text-white tracking-tight mt-2">
            {id ? 'Draw Proof' : 'Transparency'}
          </h1>
          <p className="text-sm text-[#6B6B78] mt-1">
            {id ? 'Verify the winner selection for this contest.' : 'Every winner selection is public, verifiable, and tamper-proof.'}
          </p>
        </div>

        {!id && (
          <>
            {/* Algorithm explainer */}
            <div className="rounded-2xl p-6 mb-10 space-y-5" style={{ background: '#18181C', border: '1px solid rgba(255,255,255,0.06)' }}>
              <h2 className="text-sm font-bold text-white">How Winners Are Picked</h2>
              <div className="space-y-4">
                {ALGORITHM_STEPS.map((step) => (
                  <div key={step.icon} className="flex gap-4">
                    <div className="w-7 h-7 rounded-lg bg-[rgba(91,95,239,0.15)] flex items-center justify-center text-xs font-bold text-[#5B5FEF] shrink-0">{step.icon}</div>
                    <div>
                      <p className="text-sm font-semibold text-white">{step.title}</p>
                      <p className="text-xs text-[#6B6B78] mt-0.5 leading-relaxed">{step.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <h2 className="text-lg font-bold text-white mb-5">Past Contest Results</h2>
          </>
        )}

        {id ? <ContestReport id={id} /> : <AllReports />}
      </div>
    </div>
  );
}
